alter table country drop foreign key FKs3bda8801uhqtttuaur9r6eic;
alter table department drop foreign key FKmp68t6xcos91gmiaj59fi077o;
alter table department drop foreign key FK7uo1u624kxh3ma7lxig85rcko;
alter table district drop foreign key FK276utu38g5lgqeth6pwfm3rw2;
alter table employee drop foreign key FKbejtwvg9bxus2mffsm3swj3u9;
alter table employee drop foreign key FK3qan7dnbwrvqngcqup9h9a1tt;
alter table employee drop foreign key FKqu3oj2fybl0vyb7nwonrr2ovj;
alter table job_history drop foreign key FKjo9yhubhvo4qefb2t36e619s7;
alter table job_history drop foreign key FK3j9mpn82on45fsk7ah4tps67o;
alter table job_history drop foreign key FK1qikydvi1h4879h5mkvpddnu5;
alter table province drop foreign key FKipakwfceswwc0lb3esew9hqqv;
alter table ward drop foreign key FKslko72wj5nauqvsgefqkvwpsb;
drop table if exists country;
drop table if exists department;
drop table if exists district;
drop table if exists employee;
drop table if exists job;
drop table if exists job_history;
drop table if exists province;
drop table if exists region;
drop table if exists ward;
create table country (id bigint not null, name nvarchar(255) not null, region_id bigint not null, primary key (id)) engine=InnoDB;
create table department (id bigint not null auto_increment, manager_id bigint, name nvarchar(255) not null, ward_id bigint not null, primary key (id)) engine=InnoDB;
create table district (id bigint not null, name nvarchar(255) not null, province_id bigint not null, primary key (id)) engine=InnoDB;
create table employee (id bigint not null auto_increment, birth_date datetime(6) not null, department_id bigint, email varchar(255) not null, gender bit not null, hire_date datetime(6) not null, job_id bigint not null, name nvarchar(255) not null, ph_number varchar(255) not null, salary double precision not null, ward_id bigint not null, primary key (id)) engine=InnoDB;
create table job (id bigint not null auto_increment, max_salary double precision not null, min_salary double precision not null, title nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table job_history (id bigint not null auto_increment, department_id bigint not null, employee_id bigint not null, end_date datetime(6) not null, job_id bigint not null, start_date datetime(6) not null, primary key (id)) engine=InnoDB;
create table province (id bigint not null, country_id bigint not null, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table region (id bigint not null, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table ward (id bigint not null, district_id bigint not null, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
alter table country add constraint FKs3bda8801uhqtttuaur9r6eic foreign key (region_id) references region (id);
alter table department add constraint FKmp68t6xcos91gmiaj59fi077o foreign key (manager_id) references employee (id);
alter table department add constraint FK7uo1u624kxh3ma7lxig85rcko foreign key (ward_id) references ward (id);
alter table district add constraint FK276utu38g5lgqeth6pwfm3rw2 foreign key (province_id) references province (id);
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
alter table employee add constraint FK3qan7dnbwrvqngcqup9h9a1tt foreign key (job_id) references job (id);
alter table employee add constraint FKqu3oj2fybl0vyb7nwonrr2ovj foreign key (ward_id) references ward (id);
alter table job_history add constraint FKjo9yhubhvo4qefb2t36e619s7 foreign key (department_id) references department (id);
alter table job_history add constraint FK3j9mpn82on45fsk7ah4tps67o foreign key (employee_id) references employee (id);
alter table job_history add constraint FK1qikydvi1h4879h5mkvpddnu5 foreign key (job_id) references job (id);
alter table province add constraint FKipakwfceswwc0lb3esew9hqqv foreign key (country_id) references country (id);
alter table ward add constraint FKslko72wj5nauqvsgefqkvwpsb foreign key (district_id) references district (id);
alter table country drop foreign key FKs3bda8801uhqtttuaur9r6eic;
alter table department drop foreign key FKmp68t6xcos91gmiaj59fi077o;
alter table department drop foreign key FK7uo1u624kxh3ma7lxig85rcko;
alter table district drop foreign key FK276utu38g5lgqeth6pwfm3rw2;
alter table employee drop foreign key FKbejtwvg9bxus2mffsm3swj3u9;
alter table employee drop foreign key FK3qan7dnbwrvqngcqup9h9a1tt;
alter table employee drop foreign key FKqu3oj2fybl0vyb7nwonrr2ovj;
alter table job_history drop foreign key FKjo9yhubhvo4qefb2t36e619s7;
alter table job_history drop foreign key FK3j9mpn82on45fsk7ah4tps67o;
alter table job_history drop foreign key FK1qikydvi1h4879h5mkvpddnu5;
alter table province drop foreign key FKipakwfceswwc0lb3esew9hqqv;
alter table ward drop foreign key FKslko72wj5nauqvsgefqkvwpsb;
drop table if exists country;
drop table if exists department;
drop table if exists district;
drop table if exists employee;
drop table if exists job;
drop table if exists job_history;
drop table if exists province;
drop table if exists region;
drop table if exists ward;
create table country (id bigint not null, name nvarchar(255) not null, region_id bigint not null, primary key (id)) engine=InnoDB;
create table department (id bigint not null auto_increment, manager_id bigint, name nvarchar(255) not null, ward_id bigint not null, primary key (id)) engine=InnoDB;
create table district (id bigint not null, name nvarchar(255) not null, province_id bigint not null, primary key (id)) engine=InnoDB;
create table employee (id bigint not null auto_increment, birth_date datetime(6) not null, department_id bigint, email varchar(255) not null, gender bit not null, hire_date datetime(6) not null, job_id bigint not null, name nvarchar(255) not null, ph_number varchar(255) not null, salary double precision not null, ward_id bigint not null, primary key (id)) engine=InnoDB;
create table job (id bigint not null auto_increment, max_salary double precision not null, min_salary double precision not null, title nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table job_history (id bigint not null auto_increment, department_id bigint not null, employee_id bigint not null, end_date datetime(6) not null, job_id bigint not null, start_date datetime(6) not null, primary key (id)) engine=InnoDB;
create table province (id bigint not null, country_id bigint not null, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table region (id bigint not null, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table ward (id bigint not null, district_id bigint not null, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
alter table country add constraint FKs3bda8801uhqtttuaur9r6eic foreign key (region_id) references region (id);
alter table department add constraint FKmp68t6xcos91gmiaj59fi077o foreign key (manager_id) references employee (id);
alter table department add constraint FK7uo1u624kxh3ma7lxig85rcko foreign key (ward_id) references ward (id);
alter table district add constraint FK276utu38g5lgqeth6pwfm3rw2 foreign key (province_id) references province (id);
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
alter table employee add constraint FK3qan7dnbwrvqngcqup9h9a1tt foreign key (job_id) references job (id);
alter table employee add constraint FKqu3oj2fybl0vyb7nwonrr2ovj foreign key (ward_id) references ward (id);
alter table job_history add constraint FKjo9yhubhvo4qefb2t36e619s7 foreign key (department_id) references department (id);
alter table job_history add constraint FK3j9mpn82on45fsk7ah4tps67o foreign key (employee_id) references employee (id);
alter table job_history add constraint FK1qikydvi1h4879h5mkvpddnu5 foreign key (job_id) references job (id);
alter table province add constraint FKipakwfceswwc0lb3esew9hqqv foreign key (country_id) references country (id);
alter table ward add constraint FKslko72wj5nauqvsgefqkvwpsb foreign key (district_id) references district (id);
alter table country drop foreign key FKs3bda8801uhqtttuaur9r6eic;
alter table department drop foreign key FKmp68t6xcos91gmiaj59fi077o;
alter table department drop foreign key FK7uo1u624kxh3ma7lxig85rcko;
alter table district drop foreign key FK276utu38g5lgqeth6pwfm3rw2;
alter table employee drop foreign key FKbejtwvg9bxus2mffsm3swj3u9;
alter table employee drop foreign key FK3qan7dnbwrvqngcqup9h9a1tt;
alter table employee drop foreign key FKqu3oj2fybl0vyb7nwonrr2ovj;
alter table job_history drop foreign key FKjo9yhubhvo4qefb2t36e619s7;
alter table job_history drop foreign key FK3j9mpn82on45fsk7ah4tps67o;
alter table job_history drop foreign key FK1qikydvi1h4879h5mkvpddnu5;
alter table province drop foreign key FKipakwfceswwc0lb3esew9hqqv;
alter table ward drop foreign key FKslko72wj5nauqvsgefqkvwpsb;
drop table if exists country;
drop table if exists department;
drop table if exists district;
drop table if exists employee;
drop table if exists job;
drop table if exists job_history;
drop table if exists province;
drop table if exists region;
drop table if exists ward;
create table country (id bigint not null auto_increment, name nvarchar(255) not null, region_id bigint not null, primary key (id)) engine=InnoDB;
create table department (id bigint not null auto_increment, manager_id bigint, name nvarchar(255) not null, ward_id bigint not null, primary key (id)) engine=InnoDB;
create table district (id bigint not null auto_increment, name nvarchar(255) not null, province_id bigint not null, primary key (id)) engine=InnoDB;
create table employee (id bigint not null auto_increment, birth_date datetime(6) not null, department_id bigint, email varchar(255) not null, gender bit not null, hire_date datetime(6) not null, job_id bigint not null, name nvarchar(255) not null, ph_number varchar(255) not null, salary double precision not null, ward_id bigint not null, primary key (id)) engine=InnoDB;
create table job (id bigint not null auto_increment, max_salary double precision not null, min_salary double precision not null, title nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table job_history (id bigint not null auto_increment, department_id bigint not null, employee_id bigint not null, end_date datetime(6) not null, job_id bigint not null, start_date datetime(6) not null, primary key (id)) engine=InnoDB;
create table province (id bigint not null auto_increment, country_id bigint not null, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table region (id bigint not null auto_increment, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table ward (id bigint not null auto_increment, district_id bigint not null, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
alter table country add constraint FKs3bda8801uhqtttuaur9r6eic foreign key (region_id) references region (id);
alter table department add constraint FKmp68t6xcos91gmiaj59fi077o foreign key (manager_id) references employee (id);
alter table department add constraint FK7uo1u624kxh3ma7lxig85rcko foreign key (ward_id) references ward (id);
alter table district add constraint FK276utu38g5lgqeth6pwfm3rw2 foreign key (province_id) references province (id);
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
alter table employee add constraint FK3qan7dnbwrvqngcqup9h9a1tt foreign key (job_id) references job (id);
alter table employee add constraint FKqu3oj2fybl0vyb7nwonrr2ovj foreign key (ward_id) references ward (id);
alter table job_history add constraint FKjo9yhubhvo4qefb2t36e619s7 foreign key (department_id) references department (id);
alter table job_history add constraint FK3j9mpn82on45fsk7ah4tps67o foreign key (employee_id) references employee (id);
alter table job_history add constraint FK1qikydvi1h4879h5mkvpddnu5 foreign key (job_id) references job (id);
alter table province add constraint FKipakwfceswwc0lb3esew9hqqv foreign key (country_id) references country (id);
alter table ward add constraint FKslko72wj5nauqvsgefqkvwpsb foreign key (district_id) references district (id);
alter table country drop foreign key FKs3bda8801uhqtttuaur9r6eic;
alter table department drop foreign key FKmp68t6xcos91gmiaj59fi077o;
alter table department drop foreign key FK7uo1u624kxh3ma7lxig85rcko;
alter table district drop foreign key FK276utu38g5lgqeth6pwfm3rw2;
alter table employee drop foreign key FKbejtwvg9bxus2mffsm3swj3u9;
alter table employee drop foreign key FK3qan7dnbwrvqngcqup9h9a1tt;
alter table employee drop foreign key FKqu3oj2fybl0vyb7nwonrr2ovj;
alter table job_history drop foreign key FKjo9yhubhvo4qefb2t36e619s7;
alter table job_history drop foreign key FK3j9mpn82on45fsk7ah4tps67o;
alter table job_history drop foreign key FK1qikydvi1h4879h5mkvpddnu5;
alter table province drop foreign key FKipakwfceswwc0lb3esew9hqqv;
alter table ward drop foreign key FKslko72wj5nauqvsgefqkvwpsb;
drop table if exists country;
drop table if exists department;
drop table if exists district;
drop table if exists employee;
drop table if exists job;
drop table if exists job_history;
drop table if exists province;
drop table if exists region;
drop table if exists ward;
create table country (id bigint not null auto_increment, name nvarchar(255) not null, region_id bigint not null, primary key (id)) engine=InnoDB;
create table department (id bigint not null auto_increment, manager_id bigint, name nvarchar(255) not null, ward_id bigint not null, primary key (id)) engine=InnoDB;
create table district (id bigint not null auto_increment, name nvarchar(255) not null, province_id bigint not null, primary key (id)) engine=InnoDB;
create table employee (id bigint not null auto_increment, birth_date datetime(6) not null, department_id bigint, email varchar(255) not null, gender bit not null, hire_date datetime(6) not null, job_id bigint not null, name nvarchar(255) not null, ph_number varchar(255) not null, salary double precision not null, ward_id bigint not null, primary key (id)) engine=InnoDB;
create table job (id bigint not null auto_increment, max_salary double precision not null, min_salary double precision not null, title nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table job_history (id bigint not null auto_increment, department_id bigint not null, employee_id bigint not null, end_date datetime(6) not null, job_id bigint not null, start_date datetime(6) not null, primary key (id)) engine=InnoDB;
create table province (id bigint not null auto_increment, country_id bigint not null, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table region (id bigint not null auto_increment, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table ward (id bigint not null auto_increment, district_id bigint not null, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
alter table country add constraint FKs3bda8801uhqtttuaur9r6eic foreign key (region_id) references region (id);
alter table department add constraint FKmp68t6xcos91gmiaj59fi077o foreign key (manager_id) references employee (id);
alter table department add constraint FK7uo1u624kxh3ma7lxig85rcko foreign key (ward_id) references ward (id);
alter table district add constraint FK276utu38g5lgqeth6pwfm3rw2 foreign key (province_id) references province (id);
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
alter table employee add constraint FK3qan7dnbwrvqngcqup9h9a1tt foreign key (job_id) references job (id);
alter table employee add constraint FKqu3oj2fybl0vyb7nwonrr2ovj foreign key (ward_id) references ward (id);
alter table job_history add constraint FKjo9yhubhvo4qefb2t36e619s7 foreign key (department_id) references department (id);
alter table job_history add constraint FK3j9mpn82on45fsk7ah4tps67o foreign key (employee_id) references employee (id);
alter table job_history add constraint FK1qikydvi1h4879h5mkvpddnu5 foreign key (job_id) references job (id);
alter table province add constraint FKipakwfceswwc0lb3esew9hqqv foreign key (country_id) references country (id);
alter table ward add constraint FKslko72wj5nauqvsgefqkvwpsb foreign key (district_id) references district (id);
alter table country drop foreign key FKs3bda8801uhqtttuaur9r6eic;
alter table department drop foreign key FKmp68t6xcos91gmiaj59fi077o;
alter table department drop foreign key FK7uo1u624kxh3ma7lxig85rcko;
alter table district drop foreign key FK276utu38g5lgqeth6pwfm3rw2;
alter table employee drop foreign key FKbejtwvg9bxus2mffsm3swj3u9;
alter table employee drop foreign key FK3qan7dnbwrvqngcqup9h9a1tt;
alter table employee drop foreign key FKqu3oj2fybl0vyb7nwonrr2ovj;
alter table job_history drop foreign key FKjo9yhubhvo4qefb2t36e619s7;
alter table job_history drop foreign key FK3j9mpn82on45fsk7ah4tps67o;
alter table job_history drop foreign key FK1qikydvi1h4879h5mkvpddnu5;
alter table province drop foreign key FKipakwfceswwc0lb3esew9hqqv;
alter table ward drop foreign key FKslko72wj5nauqvsgefqkvwpsb;
drop table if exists country;
drop table if exists department;
drop table if exists district;
drop table if exists employee;
drop table if exists job;
drop table if exists job_history;
drop table if exists province;
drop table if exists region;
drop table if exists ward;
create table country (id bigint not null auto_increment, name nvarchar(255) not null, region_id bigint not null, primary key (id)) engine=InnoDB;
create table department (id bigint not null auto_increment, manager_id bigint, name nvarchar(255) not null, ward_id bigint not null, primary key (id)) engine=InnoDB;
create table district (id bigint not null auto_increment, name nvarchar(255) not null, province_id bigint not null, primary key (id)) engine=InnoDB;
create table employee (id bigint not null auto_increment, birth_date datetime(6) not null, department_id bigint, email varchar(255) not null, gender bit not null, hire_date datetime(6) not null, job_id bigint not null, name nvarchar(255) not null, ph_number varchar(255) not null, salary double precision not null, ward_id bigint not null, primary key (id)) engine=InnoDB;
create table job (id bigint not null auto_increment, max_salary double precision not null, min_salary double precision not null, title nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table job_history (id bigint not null auto_increment, department_id bigint not null, employee_id bigint not null, end_date datetime(6), job_id bigint not null, start_date datetime(6) not null, primary key (id)) engine=InnoDB;
create table province (id bigint not null auto_increment, country_id bigint not null, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table region (id bigint not null auto_increment, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table ward (id bigint not null auto_increment, district_id bigint not null, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
alter table department add constraint UK_1t68827l97cwyxo9r1u6t4p7d unique (name);
alter table job add constraint UK_8vgcbp37ert4cyxml4eb3rvgo unique (title);
alter table country add constraint FKs3bda8801uhqtttuaur9r6eic foreign key (region_id) references region (id);
alter table department add constraint FKmp68t6xcos91gmiaj59fi077o foreign key (manager_id) references employee (id);
alter table department add constraint FK7uo1u624kxh3ma7lxig85rcko foreign key (ward_id) references ward (id);
alter table district add constraint FK276utu38g5lgqeth6pwfm3rw2 foreign key (province_id) references province (id);
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
alter table employee add constraint FK3qan7dnbwrvqngcqup9h9a1tt foreign key (job_id) references job (id);
alter table employee add constraint FKqu3oj2fybl0vyb7nwonrr2ovj foreign key (ward_id) references ward (id);
alter table job_history add constraint FKjo9yhubhvo4qefb2t36e619s7 foreign key (department_id) references department (id);
alter table job_history add constraint FK3j9mpn82on45fsk7ah4tps67o foreign key (employee_id) references employee (id);
alter table job_history add constraint FK1qikydvi1h4879h5mkvpddnu5 foreign key (job_id) references job (id);
alter table province add constraint FKipakwfceswwc0lb3esew9hqqv foreign key (country_id) references country (id);
alter table ward add constraint FKslko72wj5nauqvsgefqkvwpsb foreign key (district_id) references district (id);
alter table country drop foreign key FKs3bda8801uhqtttuaur9r6eic;
alter table department drop foreign key FKmp68t6xcos91gmiaj59fi077o;
alter table department drop foreign key FK7uo1u624kxh3ma7lxig85rcko;
alter table district drop foreign key FK276utu38g5lgqeth6pwfm3rw2;
alter table employee drop foreign key FKbejtwvg9bxus2mffsm3swj3u9;
alter table employee drop foreign key FK3qan7dnbwrvqngcqup9h9a1tt;
alter table employee drop foreign key FKqu3oj2fybl0vyb7nwonrr2ovj;
alter table job_history drop foreign key FKjo9yhubhvo4qefb2t36e619s7;
alter table job_history drop foreign key FK3j9mpn82on45fsk7ah4tps67o;
alter table job_history drop foreign key FK1qikydvi1h4879h5mkvpddnu5;
alter table province drop foreign key FKipakwfceswwc0lb3esew9hqqv;
alter table ward drop foreign key FKslko72wj5nauqvsgefqkvwpsb;
drop table if exists country;
drop table if exists department;
drop table if exists district;
drop table if exists employee;
drop table if exists job;
drop table if exists job_history;
drop table if exists province;
drop table if exists region;
drop table if exists ward;
create table country (id bigint not null auto_increment, name nvarchar(255) not null, region_id bigint not null, primary key (id)) engine=InnoDB;
create table department (id bigint not null auto_increment, manager_id bigint, name nvarchar(255) not null, ward_id bigint not null, primary key (id)) engine=InnoDB;
create table district (id bigint not null auto_increment, name nvarchar(255) not null, province_id bigint not null, primary key (id)) engine=InnoDB;
create table employee (id bigint not null auto_increment, birth_date datetime(6) not null, department_id bigint, email varchar(255) not null, gender bit not null, hire_date datetime(6) not null, job_id bigint not null, name nvarchar(255) not null, ph_number varchar(255) not null, salary double precision not null, ward_id bigint not null, primary key (id)) engine=InnoDB;
create table job (id bigint not null auto_increment, max_salary double precision not null, min_salary double precision not null, title nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table job_history (id bigint not null auto_increment, department_id bigint not null, employee_id bigint not null, end_date datetime(6), job_id bigint not null, start_date datetime(6) not null, primary key (id)) engine=InnoDB;
create table province (id bigint not null auto_increment, country_id bigint not null, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table region (id bigint not null auto_increment, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
create table ward (id bigint not null auto_increment, district_id bigint not null, name nvarchar(255) not null, primary key (id)) engine=InnoDB;
alter table department add constraint UK_1t68827l97cwyxo9r1u6t4p7d unique (name);
alter table job add constraint UK_8vgcbp37ert4cyxml4eb3rvgo unique (title);
alter table country add constraint FKs3bda8801uhqtttuaur9r6eic foreign key (region_id) references region (id);
alter table department add constraint FKmp68t6xcos91gmiaj59fi077o foreign key (manager_id) references employee (id);
alter table department add constraint FK7uo1u624kxh3ma7lxig85rcko foreign key (ward_id) references ward (id);
alter table district add constraint FK276utu38g5lgqeth6pwfm3rw2 foreign key (province_id) references province (id);
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
alter table employee add constraint FK3qan7dnbwrvqngcqup9h9a1tt foreign key (job_id) references job (id);
alter table employee add constraint FKqu3oj2fybl0vyb7nwonrr2ovj foreign key (ward_id) references ward (id);
alter table job_history add constraint FKjo9yhubhvo4qefb2t36e619s7 foreign key (department_id) references department (id);
alter table job_history add constraint FK3j9mpn82on45fsk7ah4tps67o foreign key (employee_id) references employee (id);
alter table job_history add constraint FK1qikydvi1h4879h5mkvpddnu5 foreign key (job_id) references job (id);
alter table province add constraint FKipakwfceswwc0lb3esew9hqqv foreign key (country_id) references country (id);
alter table ward add constraint FKslko72wj5nauqvsgefqkvwpsb foreign key (district_id) references district (id);
